url: https://offscale.io
baseurl:

# Site settings
title: Offload and upscale with <u>offscale.io</u>
email: samuel@offscale.io
description: "We've built an open hybrid multicloud which we use to setup CI/CD and Big Data pipelines. You can also use it for multicloud IaaS."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
