import { DocTranslations, CodeExample, CDDOutput } from './types';
/**
 * Progressive Enhancement for API Documentation.
 * Provides interactive features like global language sync and search.
 * No frameworks used.
 */
/**
 * Initializes the API documentation interactive features within a specific container.
 * @param container The DOM element containing the API documentation layout.
 * @param customTranslations Optional custom string dictionary for i18n
 */
export declare function initApiDocs(container?: Document | HTMLElement, customTranslations?: Partial<DocTranslations>): void;
/**
 * Web Component for CDD API Documentation
 * Usage: <cdd-api-docs spec="..."></cdd-api-docs>
 */
export declare class CDDApiDocs extends HTMLElement {
    private _translations;
    private _sdkExamples;
    constructor();
    /**
     * Gets the current custom translations applied to the UI.
     * @returns A partial DocTranslations object
     */
    get translations(): Partial<DocTranslations>;
    /**
     * Sets custom translations for the UI and triggers a re-render.
     * @param val A partial DocTranslations object
     */
    set translations(val: Partial<DocTranslations>);
    /**
     * Gets the current list of SDK examples.
     * @returns Array of CodeExample objects
     */
    get sdkExamples(): CodeExample[] | string | CDDOutput | CDDOutput[];
    /**
     * Sets the SDK examples. Automatically parses JSON strings or standardizes format, then triggers re-render.
     * When receiving snippets generated by 'to_docs_json', it securely unpacks the 'endpoints' map from
     * a `docs.json` wrapper into flat CodeExample entries.
     *
     * Expected `docs.json` Schema Layout:
     * \`\`\`json
     * {
     *   "endpoints": {
     *     "/path/to/resource": {
     *       "get": "client.getResource()",
     *       "post": "client.createResource(data)"
     *     }
     *   }
     * }
     * \`\`\`
     *
     * It preserves the 'language' attribute of the wrapper CodeExample so the correct tabs are highlighted.
     *
     * @param val Examples configuration array, string, or object. Raw code files are passed as-is.
     */
    set sdkExamples(val: CodeExample[] | string | CDDOutput | CDDOutput[]);
    /**
     * Called when the element is inserted into the DOM.
     */
    connectedCallback(): void;
    private triggerRender;
    /**
     * Renders the given OpenAPI specification string
     * @param specContent JSON or YAML string, or a URL starting with http:// or https://
     */
    renderSpec(specContent: string): Promise<void>;
    private setupPostMessage;
    /**
     * List of attributes to observe for changes.
     */
    static get observedAttributes(): string[];
    /**
     * Called when an observed attribute is changed.
     * @param name The name of the attribute
     * @param oldValue The old value
     * @param newValue The new value
     */
    attributeChangedCallback(name: string, oldValue: string, newValue: string): void;
}
